name: Build PicX

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: XPoet/picx
        path: picx 
    - name: Setup Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install
      run: cd picx && npm install
    - name: Build
      run: cd picx && npm run build
