# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build PicX

on:
  push:
    branches: [ "picx" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: XPoet/picx
        path: picx
        
    - name: Setup Node.js v14.x
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Install
      run: cd picx && npm install

    - name: Build
      run: cd picx && npm run build

